In [ ]:
import numpy as np

vector = np.random.randint(1, 10, (4,4))

print(vector)

print(np.mean(vector))          # mean of entire vector
print(np.mean(vector[1, :]))    # mean of row 1 from starting of column to end of column
print(vector[1, :])

[[4 2 5 5]
 [5 8 2 6]
 [9 1 7 1]
 [1 5 5 2]]
4.25
5.25
[5 8 2 6]
