# A FULL **ARRAY** FEATURES

In [1]:
import numpy as np

# =========================
# 1. Array Creation
# =========================
a = np.array([1, 2, 3, 4, 5])            # 1D array from list
b = np.arange(0, 10, 2)                   # 0 to 9 with step 2
c = np.zeros((2, 3))                      # 2x3 array of zeros
d = np.ones((3, 2))                       # 3x2 array of ones
e = np.eye(3)                             # 3x3 identity matrix
f = np.linspace(0, 1, 5)                  # 5 points evenly spaced between 0 and 1
g = np.random.rand(2, 2)                  # 2x2 random numbers between 0 and 1
h = np.random.randint(0, 10, size=(3, 3)) # 3x3 random integers from 0 to 9

print("a:", a)
print("b:", b)
print("c:\n", c)
print("d:\n", d)
print("e:\n", e)
print("f:", f)
print("g:\n", g)
print("h:\n", h)

# =========================
# 2. Indexing & Slicing
# =========================
print("a[0]:", a[0])          # first element
print("a[-1]:", a[-1])        # last element
print("a[1:4]:", a[1:4])      # slice
print("h[0,1]:", h[0,1])      # element at row 0 column 1
print("h[:,1]:", h[:,1])      # all rows, column 1
print("h[1,:]:", h[1,:])      # row 1, all columns

# =========================
# 3. Array Operations
# =========================
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("arr1 + arr2:", arr1 + arr2)   # element-wise addition
print("arr1 - arr2:", arr1 - arr2)   # element-wise subtraction
print("arr1 * arr2:", arr1 * arr2)   # element-wise multiplication
print("arr1 / arr2:", arr1 / arr2)   # element-wise division
print("arr1 ** 2:", arr1 ** 2)       # element-wise power

# =========================
# 4. Aggregate Functions
# =========================
arr = np.array([1,2,3,4,5])
print("sum:", arr.sum())
print("mean:", arr.mean())
print("min:", arr.min())
print("max:", arr.max())
print("standard deviation:", arr.std())

# =========================
# 5. Reshape & Flatten
# =========================
arr = np.arange(12)
print("Original:", arr)
arr2d = arr.reshape((3,4))   # reshape to 3x4
print("Reshaped 3x4:\n", arr2d)
print("Flattened:", arr2d.flatten())

# =========================
# 6. Stacking Arrays
# =========================
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
h_stack = np.hstack((a1,a2))  # horizontal stack
v_stack = np.vstack((a1,a2))  # vertical stack
print("Horizontal stack:", h_stack)
print("Vertical stack:\n", v_stack)

# =========================
# 7. Boolean Indexing & Conditions
# =========================
arr = np.arange(10)
evens = arr[arr % 2 == 0]      # only even numbers
print("Evens:", evens)
greater5 = arr[arr > 5]        # numbers greater than 5
print("Greater than 5:", greater5)

# =========================
# 8. Copy vs View
# =========================
arr = np.array([1,2,3])
arr_copy = arr.copy()   # independent copy
arr_view = arr.view()   # shared data
arr[0] = 100
print("Original:", arr)
print("Copy:", arr_copy)
print("View:", arr_view)

# =========================
# 9. Mathematical Functions
# =========================
arr = np.array([1,4,9])
print("sqrt:", np.sqrt(arr))
print("log:", np.log(arr))
print("exp:", np.exp(arr))
print("sin:", np.sin(arr))

# =========================
# 10. Concatenate & Stack
# =========================
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
finalArr = np.concatenate((arr1, arr2))
print("Concatenated:", finalArr)


a: [1 2 3 4 5]
b: [0 2 4 6 8]
c:
 [[0. 0. 0.]
 [0. 0. 0.]]
d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
e:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
f: [0.   0.25 0.5  0.75 1.  ]
g:
 [[0.4553595  0.38800957]
 [0.14029333 0.39179917]]
h:
 [[7 5 8]
 [2 7 2]
 [6 9 3]]
a[0]: 1
a[-1]: 5
a[1:4]: [2 3 4]
h[0,1]: 5
h[:,1]: [5 7 9]
h[1,:]: [2 7 2]
arr1 + arr2: [5 7 9]
arr1 - arr2: [-3 -3 -3]
arr1 * arr2: [ 4 10 18]
arr1 / arr2: [0.25 0.4  0.5 ]
arr1 ** 2: [1 4 9]
sum: 15
mean: 3.0
min: 1
max: 5
standard deviation: 1.4142135623730951
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Horizontal stack: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Evens: [0 2 4 6 8]
Greater than 5: [6 7 8 9]
Original: [100   2   3]
Copy: [1 2 3]
View: [100   2   3]
sqrt: [1. 2. 3.]
log: [0.         1.38629436 2.19722458]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
sin: [ 0.84147098 -0.7568025   0.41211849]
Concat