zeros

In [1]:
import numpy as np

a = np.zeros((4,3))     # will make a 4 x 3 vector with all zeros as its elements
a1 = np.zeros((4))      # 1x4
a2 = np.zeros((4, 1))   # 4x1
print(a)
print('\n',a1)
print('\n',a2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [0. 0. 0. 0.]

 [[0.]
 [0.]
 [0.]
 [0.]]


ones

In [2]:
b = np.ones((3,2))      # will make a 3x2 array of elements as 1
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


eye - makes identity matrix

In [3]:
c = np.eye(3)       # 3x3
c1 = np.eye(3,4)    # 3x4
print(c)
print('\n',c1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


linspace

np.linspace() is used to create evenly spaced numbers over a specified interval. Unlike arange, which uses a step size, linspace specifies the number of points you want.

In [4]:
d = np.linspace(0, 1, 5)                  # 5 points evenly spaced between 0 and 1
print(d)

[0.   0.25 0.5  0.75 1.  ]


random.rand & random.randiant & (Indexing and Slicing)

In [5]:
e = np.random.rand(3,3)             # 3x3 vector with random numbers btwn 0 to 1
print(e)

e1 = np.random.randint(0,9, (4,4))  # makes a 4x4 vector with random nums from 0 to 9
print('*'*50)
print('\n',e1)

# Indexing 
print('*'*50)
print("\n a[0]:", a[0])             # first element (if its a 3x3 or 2x2 vector it will give first elements in the first row)
print("\n a[-1]:", a[-1])           # last element

# slice
print('*'*50)
print("\n element in row 0, column 1 --", e1[0,1])                  # row 0 column 1 element
print("\n", e1[1:4])                                                # slice         (suppose a vector is 6x6 then it will only print from idx 1 to idx 3 [4 is exclusive] )
print("\n printing column 1 (from starting to end) -- ", e1[:,1])   # (start : end, column)  
print("\n printing column 1 (from idx 0 to end) -- ", e1[0:,1])     # (idx[0] : end, column)
print("\n printng row 1 (from starting to end) -- ", e1[1,:])       # (row, start : end)
print("\n printng row 0 (from idx 1 to idx 4) -- ", e1[0,1:5])      # (row, start : end)


[[0.21884473 0.45246081 0.46492492]
 [0.41569627 0.20419661 0.5673539 ]
 [0.5744511  0.06120549 0.57769355]]
**************************************************

 [[7 0 0 3]
 [2 1 4 3]
 [1 1 3 4]
 [6 6 3 2]]
**************************************************

 a[0]: [0. 0. 0.]

 a[-1]: [0. 0. 0.]
**************************************************

 element in row 0, column 1 -- 0

 [[2 1 4 3]
 [1 1 3 4]
 [6 6 3 2]]

 printing column 1 (from starting to end) --  [0 1 1 6]

 printing column 1 (from idx 0 to end) --  [0 1 1 6]

 printng row 1 (from starting to end) --  [2 1 4 3]

 printng row 0 (from idx 1 to idx 4) --  [0 0 3]
