In [1]:
import numpy as np

g = np.round(np.random.rand(10, 10), 2) 
h = np.arange(1, 10).reshape(3,3)

print(f"{g}\n")
print(f"{h}\n")
print(f"{h[0:3]}\n")

print(f"{h[:, 0]}\n")   # printing columns only
print(f"{h[:, 1]}\n")   # printing columns only
print(f"{h[:, 2]}\n")   # printing columns only

print(f"{h[2, 1]}\n")
print(f"{h[1, 2]}\n")

""" 
for printing row and columns we use slicing " : "
for printing element at specific indexes we use commas " , "
"""

[[0.23 0.7  0.64 0.49 0.59 0.4  0.35 0.96 0.06 0.81]
 [0.71 0.63 0.71 0.16 0.77 0.61 0.63 0.76 0.42 0.65]
 [0.24 0.65 0.21 0.77 0.38 0.88 0.23 0.81 0.72 0.16]
 [0.66 0.62 0.88 0.36 0.22 0.18 0.47 0.49 0.24 0.39]
 [0.75 0.89 0.12 0.17 0.36 0.23 0.96 0.22 0.06 0.02]
 [0.54 0.8  0.79 0.87 0.41 0.08 0.8  0.63 0.43 0.26]
 [0.88 0.13 0.23 0.85 0.03 0.85 0.65 0.9  0.78 0.95]
 [0.15 0.63 0.21 0.46 0.75 0.19 0.38 0.27 0.11 0.53]
 [0.95 0.44 0.58 0.92 0.37 0.22 0.89 0.19 0.93 0.51]
 [0.4  0.27 0.47 0.36 0.92 0.9  0.21 0.46 0.5  0.15]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 4 7]

[2 5 8]

[3 6 9]

8

6



' \nfor printing row and columns we use slicing " : "\nfor printing element at specific indexes we use commas " , "\n'

In [2]:
a = np.arange(1,15)
print(f"{a}\n")
a1 = a.reshape(7,2)
a2 = a.reshape(2,7)
a3 = a.reshape(1,14)
a4 = a.reshape(14,1)

print(f"7x2 \n {a1}\n")
print(f"2x7 \n {a2}\n")
print(f"1x14 \n {a3}\n")
print(f"14x1 \n {a4}\n")


b = np.arange(1,7).reshape(2,3)
print(f"b : \n {b}\n")
print(f"b Transpose : \n {b.T}\n")



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

7x2 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]

2x7 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

1x14 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]

14x1 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]

b : 
 [[1 2 3]
 [4 5 6]]

b Transpose : 
 [[1 4]
 [2 5]
 [3 6]]



In [3]:
arr = np.array([1,2,3])
arr_copy = arr.copy()   # independent copy
arr_view = arr.view()   # shared data   # Changes in the original WILL reflect in the view (and vice versa).
print("Original:", arr)

arr[0] = 100
print("\nAfter modifying the view:")
print("Original array:", arr)      # original changes too
print("View array    :", arr_view) # view shows same change



Original: [1 2 3]

After modifying the view:
Original array: [100   2   3]
View array    : [100   2   3]


In [4]:
print(f"{np.square(10)}")

# there is no specific function do cube, but you cdan do it by using power
# you only you can do cube, but also you can do power of any number
print(f"2 to the power of 2 : {np.power(2, 2)}")
print(f"2 to the power of 3 : {np.power(2, 3)}")
print(f"2 to the power of 4 : {np.power(2, 4)}")

# do not write any kind of code in jupyter, bcoz it will not run. And eventyally break down


100
2 to the power of 2 : 4
2 to the power of 3 : 8
2 to the power of 4 : 16
