# Doing Statistics

In [1]:
import numpy as np

a = np.arange(1, 15)
b = np.random.randint(1, 8, (2,3))
print(b, '\n')
print("*"*50)

print(f"mean : {np.mean(b)}\n")
print(f"standard deviation : {np.std(b)}\n")
print(f"median : {np.median(b)}\n")
print(f"median of rows : {np.median(b, axis=0)}\n")
print(f"median of 2nd column : {np.median(b[ : ,1])}\n")


[[4 4 4]
 [1 6 4]] 

**************************************************
mean : 3.8333333333333335

standard deviation : 1.462494064565354

median : 4.0

median of rows : [2.5 5.  4. ]

median of 2nd column : 5.0



Transpose -- (Storing Column data into Variables)

In [21]:
# Transpose

c = np.random.randint(1111, 10000, (25, 4))
# print(c, '\n')
print('*'*50)

data1, data2, data3, data4 = c.T        # now rows and columns both are flipped, and all the datas are taking rows now
print(f"data1 : {data1}\n")
print(f"data2 : {data2}\n")
print(f"data3 : {data3}\n")
print(f"data4 : {data4}\n")
print('*'*50)


newData = c[ : , 1: ]          # [row start : row end, 1st idx column: column end]
print(newData)
print('*'*50)
print(c[:15, 2:],'\n')
print(f"std dev. of columns : {np.round(c.std(axis=1), 2)}\n")
# print(c)
print(f"column 1 : {np.round( c[:, 1],2)}\n")
print(f"std dev. of column 0 : {np.round(np.std(c[:, 0]),2)}")
print(f"std dev. of column 1 : {np.round(np.std(c[:, 1]),2)}")
print(f"std dev. of column 2 : {np.round(np.std(c[:, 2]),2)}")
print(f"std dev. of column 3 : {np.round(np.std(c[:, 3]),2)}")


**************************************************
data1 : [7079 5042 4223 6935 1971 7801 9472 4790 7829 9798 8752 6103 7686 4962
 5102 1980 9656 7532 5103 5169 9735 7847 4537 4061 8635]

data2 : [2273 4052 5349 7972 6643 2382 6296 9152 1117 5187 5535 7152 5724 4525
 7549 4073 7817 8700 3735 7520 8596 3563 8618 2438 4074]

data3 : [8191 3046 1173 4955 2917 7072 2763 3234 8777 8300 2642 4255 3597 2412
 9060 4088 1678 9660 1176 9731 3510 5849 2643 7971 7822]

data4 : [4270 2231 6900 8732 9684 9520 1432 9790 8937 7116 9838 1125 9884 7519
 7034 7672 5201 1406 1270 8993 3369 3865 2205 3693 3999]

**************************************************
[[2273 8191 4270]
 [4052 3046 2231]
 [5349 1173 6900]
 [7972 4955 8732]
 [6643 2917 9684]
 [2382 7072 9520]
 [6296 2763 1432]
 [9152 3234 9790]
 [1117 8777 8937]
 [5187 8300 7116]
 [5535 2642 9838]
 [7152 4255 1125]
 [5724 3597 9884]
 [4525 2412 7519]
 [7549 9060 7034]
 [4073 4088 7672]
 [7817 1678 5201]
 [8700 9660 1406]
 [3735 1176 1270]
 [7520 9