# Doing Statistics

In [1]:
import numpy as np

a = np.arange(1, 15)
b = np.random.randint(1, 8, (2,3))
print(b, '\n')
print("*"*50)

print(f"mean : {np.mean(b)}\n")
print(f"standard deviation : {np.std(b)}\n")
print(f"median : {np.median(b)}\n")
print(f"median of rows : {np.median(b, axis=0)}\n")
print(f"median of 2nd column : {np.median(b[ : ,1])}\n")


[[4 4 4]
 [1 6 4]] 

**************************************************
mean : 3.8333333333333335

standard deviation : 1.462494064565354

median : 4.0

median of rows : [2.5 5.  4. ]

median of 2nd column : 5.0



Transpose -- (Storing Column data into Variables)

In [2]:
# Transpose
import numpy as np

c = np.random.randint(1111, 10000, (25, 4))
# print(c, '\n')
print('*'*50)

data1, data2, data3, data4 = c.T
print(f"data1 : {data1}\n")
print(f"data2 : {data2}\n")
print(f"data3 : {data3}\n")
print(f"data4 : {data4}\n")
print('*'*50)


newData = c[ : , 1: ]          # [row start : row end, 1st idx column: column end]
print(newData)
print('*'*50)
print(c[:15, 2:5],'\n')
print(f"std dev. of columns : {np.round(c.std(axis=1), 2)}\n")





**************************************************
data1 : [6188 9359 5112 7165 6250 4629 4361 4694 9043 4455 9344 2751 6240 9769
 3227 1334 5075 2264 8143 3906 4952 6361 5126 1498 7589]

data2 : [4867 8649 3878 2784 1732 4587 2531 5237 9891 5133 4604 8162 3115 8993
 4548 8424 2767 7904 3204 4494 1658 9338 8579 4081 9834]

data3 : [6987 2708 3677 4073 1584 2728 2318 5454 7749 8733 5040 5243 3457 3851
 5452 9428 8817 8208 4165 2715 3827 9295 7290 6741 6907]

data4 : [8600 9436 1555 6618 4346 1249 9436 6005 5344 6016 2165 7924 5735 5914
 5245 4918 1757 1489 4665 3039 2589 9967 2782 6663 8670]

**************************************************
[[4867 6987 8600]
 [8649 2708 9436]
 [3878 3677 1555]
 [2784 4073 6618]
 [1732 1584 4346]
 [4587 2728 1249]
 [2531 2318 9436]
 [5237 5454 6005]
 [9891 7749 5344]
 [5133 8733 6016]
 [4604 5040 2165]
 [8162 5243 7924]
 [3115 3457 5735]
 [8993 3851 5914]
 [4548 5452 5245]
 [8424 9428 4918]
 [2767 8817 1757]
 [7904 8208 1489]
 [3204 4165 4665]
 [4494 2