# Finding mean of a vector

In [5]:
import numpy as np

vector = np.random.randint(1, 10, (4,4))

print(vector)

print('\n',np.mean(vector))          # mean of entire vector
print('\n',np.mean(vector[1, :]))    # mean of row 1 from start to end

[[9 9 3 9]
 [1 1 7 1]
 [3 7 9 3]
 [3 1 6 2]]

 4.625

 2.5
