# Finding mean of a vector

In [ ]:
import numpy as np

vector = np.random.randint(1, 10, (4,4))

print(vector)

print('\n',np.mean(vector))          # mean of entire vector
print('\n',np.mean(vector[1, :]))    # mean of row 1 from start to end

# Copies and Views

Slicing

In [ ]:
a = np.arange(11)
print(a,'\n')

# slicing
b1 = a[ : ]  
print(b1,'\n')   

b2 = a[ : : 2]               # b storing all the values of a from 1 to 10, with a gap of 2   # (Here the values of a are not stored in b, but rather the index of a is stored in b) 
print(b2,'\n')   

b1[0] = 10                  # if you make changes in b1, the values in a will also change, bcoz we have stored the idx of a in b1
print(a, '\n')

"""
b1 is not a new independent array.
It is a view of a (it points to the same memory).
So when you change b1[0], you’re actually modifying the same underlying data in a.

THIS IS THE MAJOR DRAWBACKL OF USING SLICING, HENCE WE USE 'COPY' TO AVOID SUCH PROBLEMS
"""
print(np.shares_memory(a,b1),'\n')
print(np.shares_memory(a,b2))

Copy

In [ ]:
# copy
b3 = a[::2].copy()
print(b3, '\n')


b3[0] = 0           # only the value in b3 will change
print(a, '\n')
print(b3, '\n')
print(np.shares_memory(a, b3), '\n')

"""
In copying, the idx of a is not stored, rather the values itself of a are getting stored
"""

Fancy Indexing

(NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views)

Using boolean mask

In [ ]:
c = np.random.randint(1,10,18)
print(c,'\n')

even = (c % 2 == 0)
print(f"printing evens : {c[even]} \n")

odd = (c % 2 != 0)
print(f"printing odds : {c[odd]} \n")

c[odd] = -1                                 # here we have changed all the odd values in c into -1
print(f"the changed values in c are {c}")



Indexing with an array of integers

In [42]:
d = np.arange(0, 100, 10)
print(f"{d}\n")

d1 = d[[2,3,2,5,2,3]]           # here we made an arr from variable d with idxs of 2,3,2,5,3
print(f"{d1}\n")

d[[8, 9]] = 99                  # changing the values at given idx
print(f"{d}")

# changing the values but storing them into another variable, rather than making changes into the original variable
d2 = d.copy()
d2[0:6] = 3                      # changing multiple values simultaneously using slicing
print(f"{d2}")


[ 0 10 20 30 40 50 60 70 80 90]

[20 30 20 50 20 30]

[ 0 10 20 30 40 50 60 70 99 99]
[ 3  3  3  3  3  3 60 70 99 99]
