zeros

In [1]:
import numpy as np

a = np.zeros((4,3))     # will make a 4 x 3 vector with all zeros as its elements
a1 = np.zeros((4))      # 1x4
a2 = np.zeros((4, 1))   # 4x1
print(a)
print('\n',a1)
print('\n',a2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [0. 0. 0. 0.]

 [[0.]
 [0.]
 [0.]
 [0.]]


ones

In [14]:
b = np.ones((3,2))      # will make a 3x2 array of elements as 1
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


eye - makes identity matrix

In [3]:
c = np.eye(3)       # 3x3
c1 = np.eye(3,4)    # 3x4
print(c)
print('\n',c1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


diag - to make diagonal arr

In [4]:
obj1 = np.diag([1,2,3,4])   # for 4 values 4x4 vector, for 5 values 5x5 vector
print(obj1)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


dtype - data type

In [5]:
obj2 = np.arange(10)
print(obj2.dtype)       # data type is integer that holds 64 bit

int64


linspace (linear space)

np.linspace() is used to create evenly spaced numbers over a specified interval. Unlike arange, which uses a step size, linspace specifies the number of points you want.

In [6]:
d = np.linspace(0, 1, 5)                  # 5 points evenly spaced between 0 and 1
print(d)

[0.   0.25 0.5  0.75 1.  ]


In [17]:
d1 = np.linspace(1, 10, 5)
d1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

random.rand & random.randiant & (Indexing and Slicing)

In [19]:
e = np.random.rand(3,3)             # 3x3 vector with random numbers btwn 0 to 1
print(e)

e1 = np.random.randint(0,9, (4,4))  # makes a 4x4 vector with random nums from 0 to 9
print('*'*50)
print('\n',e1)

# Indexing 
print('*'*50)
print("\n a[0]:", a[0])             # first element (if its a 3x3 or 2x2 vector it will give first elements in the first row)
print("\n a[-1]:", a[-1])           # last element

# slice
print('*'*50)
print("\n element in row 0, column 1 --", e1[0,1])                  # row 0 column 1 element
print("\n", e1[1:4])                                                # slice         (suppose a vector is 6x6 then it will only print from idx 1 to idx 3 [4 is exclusive] )
print("\n printing column 1 (from starting to end) -- ", e1[:,1])   # (start : end, column)  
print("\n printing column 1 (from idx 0 to end) -- ", e1[0:,1])     # (idx[0] : end, column)
print("\n printng row 1 (from starting to end) -- ", e1[1,:])       # (row, start : end)
print("\n printng row 0 (from idx 1 to idx 4) -- ", e1[0,1:5])      # (row, start : end)

# using slice in range
print('*'*50)
obj5 = np.arange(11)
print(obj5)
print('\n',obj5[0 : 11 : 2])    # printing elements from 0 to 10 with the difference of 2
print('\n', obj5[0 : 11])

# changing all the elements from 6 to the end into num 9
print('*'*50)
obj5[6 : ] = 9
print(obj5)

# reversing the values
print('*'*50)
obj6 = np.arange(5)   # [0 1 2 3 4]
reversed_obj6 = obj6[::-1]
print('\n',reversed_obj6)  # [4 3 2 1 0]


[[0.10640778 0.49950093 0.13896307]
 [0.87209984 0.52937812 0.85312616]
 [0.64486565 0.37978751 0.58678246]]
**************************************************

 [[3 5 6 1]
 [6 8 0 1]
 [1 0 2 0]
 [5 5 4 5]]
**************************************************

 a[0]: [0. 0. 0.]

 a[-1]: [0. 0. 0.]
**************************************************

 element in row 0, column 1 -- 5

 [[6 8 0 1]
 [1 0 2 0]
 [5 5 4 5]]

 printing column 1 (from starting to end) --  [5 8 0 5]

 printing column 1 (from idx 0 to end) --  [5 8 0 5]

 printng row 1 (from starting to end) --  [6 8 0 1]

 printng row 0 (from idx 1 to idx 4) --  [5 6 1]
**************************************************
[ 0  1  2  3  4  5  6  7  8  9 10]

 [ 0  2  4  6  8 10]

 [ 0  1  2  3  4  5  6  7  8  9 10]
**************************************************
[0 1 2 3 4 5 9 9 9 9 9]
**************************************************

 [4 3 2 1 0]


Using operators

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("arr1 + arr2:", arr1 + arr2)   # element-wise addition
print("arr1 - arr2:", arr1 - arr2)   # element-wise subtraction
print("arr1 * arr2:", arr1 * arr2)   # element-wise multiplication
print("arr1 / arr2:", arr1 / arr2)   # element-wise division
print("arr1 ** 2:", arr1 ** 2)       # element-wise power

arr1 + arr2: [5 7 9]
arr1 - arr2: [-3 -3 -3]
arr1 * arr2: [ 4 10 18]
arr1 / arr2: [0.25 0.4  0.5 ]
arr1 ** 2: [1 4 9]


Aggregate functions

In [ ]:
arr = np.array([1,2,3,4,5])
print("sum:", arr.sum())            # sum of all arr elements
print("mean:", arr.mean())          # mean of all arr elements
print("min:", arr.min())            # min num of all arr elements
print("max:", arr.max())            # min num of all arr elements
print("standard deviation:", arr.std())     # std deviation of all arr elements
print("standard deviation:", round(arr.std(), 2))   # using round

sum: 15
mean: 3.0
min: 1
max: 5
standard deviation: 1.4142135623730951
standard deviation: 1.41


Reshape and Flatten

In [10]:
arr = np.arange(12)
print(f"original {arr}")

# reshape
arr2 = arr.reshape((3,4))       # reshaping the arr into a vector, MAKE SURE THAT ALL THE ELEMENTS IN arr MUST BE PRESENT IN arr2
print(f"{arr2}")

# flatten
print('\n Flatten ',arr2.flatten())      # bringing the vector back to an array

original [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten  [ 0  1  2  3  4  5  6  7  8  9 10 11]


Mathematical function

In [11]:
arr3 = np.array([1,4,9])
print("sqrt:", np.sqrt(arr3))                   # square root
print("log:", np.round(np.log(arr3), 2))        # log
print("exp:", np.round(np.exp(arr3), 2))        # exponential
print("sin:", np.round(np.sin(arr3), 2))

sqrt: [1. 2. 3.]
log: [0.   1.39 2.2 ]
exp: [2.72000e+00 5.46000e+01 8.10308e+03]
sin: [ 0.84 -0.76  0.41]


Stacking arrays

In [12]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

# h stack
h_stack = np.hstack((a1, a2))       # puts both the arr in a horizontal (one after another) arr format

# v stack
v_stack = np.vstack((a1, a2))       # puts both the arr in a vertical (one below another) arr format

print(h_stack)
print('\n',v_stack)


[1 2 3 4 5 6]

 [[1 2 3]
 [4 5 6]]


Making a vector

In [13]:
obj4 = np.diag([1,2,3])
print(obj4)
print('\n',obj4[2,2])       # element at second idx of row and second idx of column

# assigning values at given idx
obj4[2, 1] = 5
print('\n', obj4)           

[[1 0 0]
 [0 2 0]
 [0 0 3]]

 3

 [[1 0 0]
 [0 2 0]
 [0 5 3]]
