# Doing Statistics

In [2]:
import numpy as np

a = np.arange(1, 15)
b = np.random.randint(1, 8, (2,3))
print(b, '\n')
print("*"*50)

print(f"mean : {np.mean(b)}\n")
print(f"standard deviation : {np.std(b)}\n")
print(f"median : {np.median(b)}\n")
print(f"median of rows : {np.median(b, axis=0)}\n")
print(f"median of 2nd column : {np.median(b[ : ,1])}\n")


[[6 1 1]
 [6 7 2]] 

**************************************************
mean : 3.8333333333333335

standard deviation : 2.544056253745625

median : 4.0

median of rows : [6.  4.  1.5]

median of 2nd column : 4.0



Transpose -- (Storing Column data into Variables)

In [3]:
# Transpose

c = np.random.randint(1111, 10000, (25, 4))
# print(c, '\n')
print('*'*50)

data1, data2, data3, data4 = c.T        # now rows and columns both are flipped, and all the datas are taking rows now
print(f"data1 : {data1}\n")
print(f"data2 : {data2}\n")
print(f"data3 : {data3}\n")
print(f"data4 : {data4}\n")
print('*'*50)


newData = c[ : , 1: ]          # [row start : row end, 1st idx column: column end]
print(newData)
print('*'*50)
print(c[:15, 2:],'\n')
print(f"std dev. of columns : {np.round(c.std(axis=1), 2)}\n")
# print(c)
print(f"column 1 : {np.round( c[:, 1],2)}\n")
print(f"std dev. of column 0 : {np.round(np.std(c[:, 0]),2)}")
print(f"std dev. of column 1 : {np.round(np.std(c[:, 1]),2)}")
print(f"std dev. of column 2 : {np.round(np.std(c[:, 2]),2)}")
print(f"std dev. of column 3 : {np.round(np.std(c[:, 3]),2)}")


**************************************************
data1 : [5935 6151 6449 1546 9937 3171 5869 6963 2854 1566 2291 4020 8403 4958
 5593 6152 1428 3966 8298 7971 4401 6152 8413 8601 2900]

data2 : [2150 3214 7604 3397 1781 8810 3290 1235 3038 1748 8863 6493 5260 3898
 9839 1310 5494 4401 9995 7953 2579 2141 7992 7264 3099]

data3 : [3133 1369 2572 9450 2903 6809 6323 7178 9317 6878 3659 9601 4871 4881
 3281 3634 1988 6952 7103 4279 1290 9275 1615 2753 4410]

data4 : [1928 8297 2869 8220 7727 3065 1557 8220 1939 7036 6143 9880 9880 2589
 7153 3469 8843 7956 2331 6436 2328 3411 5439 1329 4415]

**************************************************
[[2150 3133 1928]
 [3214 1369 8297]
 [7604 2572 2869]
 [3397 9450 8220]
 [1781 2903 7727]
 [8810 6809 3065]
 [3290 6323 1557]
 [1235 7178 8220]
 [3038 9317 1939]
 [1748 6878 7036]
 [8863 3659 6143]
 [6493 9601 9880]
 [5260 4871 9880]
 [3898 4881 2589]
 [9839 3281 7153]
 [1310 3634 3469]
 [5494 1988 8843]
 [4401 6952 7956]
 [9995 7103 2331]
 [7953 4