# **BASIC REDUCTIONS**

Sums

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])

print(f"sum : {np.sum(x)}\n")

print('*'*50)
y = np.array([[1,2], [3,4]])
print(f"sum : {np.sum(y)}\n")                   # 1+2+3+4 = 10
print(f"sum axis 0 : {y.sum(axis = 0)}\n")      # culumn wise sum
print(f"sum axis 1 : {y.sum(axis = 1)}\n")      # row wise sum



print('*'*50)
z = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Total sum
print(f"Sum of all elements: {np.sum(z)}\n")  # 1+2+3+4+5+6+7+8+9 = 45

# Column-wise sum (axis=0)
print(f"Sum along axis 0 (columns): {z.sum(axis=0)}\n")  
# [1+4+7, 2+5+8, 3+6+9] → [12, 15, 18]

# Row-wise sum (axis=1)
print(f"Sum along axis 1 (rows): {z.sum(axis=1)}\n")  
# [1+2+3, 4+5+6, 7+8+9] → [6, 15, 24]

# print(f"Sum along axis 1 (rows): {z.sum(axis=2)}\n")      [YOU CANT PUT ANY OTHER VALUE OTHER THEN 0 (COLUMN) AND 1(ROW) ]  

sum : 15

**************************************************
sum : 10

sum axis 0 : [4 6]

sum axis 1 : [3 7]

**************************************************
Sum of all elements: 45

Sum along axis 0 (columns): [12 15 18]

Sum along axis 1 (rows): [ 6 15 24]



In [ ]:
a = np.arange(1, 15)
print(f"{a.min()}\n")          # 1
print(f"{a.argmin()}\n")       # 0     returns index of the min element
print(f"{a.max()}\n")          # 14
print(f"{a.argmax()}\n")       # 14    returns index of the max element


1

0

14

13



Logical Operations

In [3]:
b = np.array([1,0,1,1], dtype = bool)

print(f"All : {np.all(b)}")     # if all of them are true, then its true
print(f"Any : {np.any(b)}\n")     # if any one of them is true, then its true


# can be used for array comparisons
c  = np.zeros((5,5))
print(f"{c}\n")
print(f"Any != 0 : {np.any(c != 0)}\n")     # checks if any of them is not 0
print(f"Any == 0 : {np.all(c == 0)}\n")     # checks if all of them are 0


d1 = np.array([1,2,3,2])
d2 = np.array([2,2,3,2])
d3 = np.array([6,4,4,5])
print(np.all((d1 <= d2) & (d2 <= d3)), '\n')
print(((d1 <= d2) & (d2 <= d3)).all(), '\n')
print(np.any((d1 <= d2) & (d2 <= d3)), '\n')

"""
np.all(x) → calls the NumPy function.
x.all() → calls the array’s own method.
"""


All : False
Any : True

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Any != 0 : False

Any == 0 : True

True 

True 

True 



'\nnp.all(x) → calls the NumPy function.\nx.all() → calls the array’s own method.\n'