In [1]:
import numpy as np

# making 2D array
a = np.arange(10, 101, 10).reshape(2,5)
d = np.random.randint(1,10, (5,5))
print(a,'\n')
print(d,'\n')

# making 3D array
b = np.arange(1, 51).reshape(2,5,5)
b1 = np.arange(1, 51).reshape(1,25,2)
c = np.ones((2,4,3))
d1 = np.random.randint(1,10, (3,5,5))
print(b,'\n')
print(b1,'\n')
print(c,'\n')
print('Making random integers : \n',d1,'\n')








[[ 10  20  30  40  50]
 [ 60  70  80  90 100]] 

[[2 1 8 9 2]
 [1 3 5 6 6]
 [9 7 5 7 5]
 [6 7 2 7 7]
 [5 3 6 1 1]] 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]
  [25 26]
  [27 28]
  [29 30]
  [31 32]
  [33 34]
  [35 36]
  [37 38]
  [39 40]
  [41 42]
  [43 44]
  [45 46]
  [47 48]
  [49 50]]] 

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]] 

Making random integers : 
 [[[4 2 3 7 3]
  [7 9 7 8 1]
  [6 6 9 9 9]
  [2 4 6 5 5]
  [8 5 3 5 9]]

 [[5 3 2 6 7]
  [8 7 7 9 4]
  [8 1 5 1 3]
  [9 1 8 4 8]
  [3 7 1 8 3]]

 [[2 4 3 4 4]
  [4 9 8 7 4]
  [6 3 5 8 6]
  [4 5 6 9 1]
  [9 9 1 5 6]]] 



In [2]:
e = np.random.randint(1,10, (2,3,5,5))

print(e)
# check for doubt at home


[[[[6 2 6 9 3]
   [6 8 6 4 2]
   [7 6 9 1 8]
   [3 8 9 1 1]
   [4 4 5 5 1]]

  [[1 2 9 5 4]
   [5 5 7 6 6]
   [3 5 6 1 2]
   [4 7 5 2 5]
   [4 2 6 2 6]]

  [[1 8 7 6 5]
   [9 7 6 2 3]
   [1 2 8 4 9]
   [6 8 2 6 5]
   [8 1 1 1 4]]]


 [[[1 5 1 3 7]
   [5 7 3 5 9]
   [9 7 7 8 9]
   [3 7 8 9 8]
   [1 3 1 3 4]]

  [[8 5 1 5 6]
   [8 8 8 6 9]
   [8 6 2 1 7]
   [9 5 7 6 6]
   [9 4 1 1 9]]

  [[3 9 4 9 5]
   [6 5 9 3 9]
   [1 4 2 5 5]
   [2 6 3 4 4]
   [6 3 3 5 5]]]]


In [3]:
# using tile
n = np.arange(0, 40, 10)
f = np.tile(n, (4,2))
print(f"f -- \n {f} \n")

f1 = np.tile(n, (4,2))
print(f"f1 -- \n {f1} \n")

print(f"f * f1 : \n {f*f1} \n")

# using Transpose
f1_Transpose = f1.T
print(f"f1.T -- \n {f1_Transpose} \n")



f -- 
 [[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]] 

f1 -- 
 [[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]] 

f * f1 : 
 [[  0 100 400 900   0 100 400 900]
 [  0 100 400 900   0 100 400 900]
 [  0 100 400 900   0 100 400 900]
 [  0 100 400 900   0 100 400 900]] 

f1.T -- 
 [[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]
 [ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]] 

