# **ELEMENT WISE OPERATIONS**

1. Basic operations

    with scalars

In [4]:
import numpy as np


a = np.arange(5)
print(f"{a}\n")                               # will do +1 into all the elements in a
print(f"{a+1}\n")                               # will do +1 into all the elements in a
print(f"{a**2}\n")

[0 1 2 3 4]

[1 2 3 4 5]

[ 0  1  4  9 16]



All arithmatic operations element wise

In [3]:
b = np.ones((5))
print(f"{b}\n")
print(f"{b+1}\n")
print(f"{a-b}\n")       # make sure that the element numbers in a is same as element numbers in b
print(f"{a*b}\n")


# doing the same in matrix
print('*'*50)
c = np.diag([1,2,3,4])
print(f"c\n {c}\n")
print(f"c*2\n {c*2}\n")
print(f"c+1\n {c+1}\n")
print(f"c*c\n {c*c}\n")
    # print(f"c.dot(c)\n {c.dot(c)}\n")     [you can also do this for c*c]

[1. 1. 1. 1. 1.]

[2. 2. 2. 2. 2.]

[-1.  0.  1.  2.  3.]

[0. 1. 2. 3. 4.]

**************************************************
c
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

c*2
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]

c+1
 [[2 1 1 1]
 [1 3 1 1]
 [1 1 4 1]
 [1 1 1 5]]

c*c
 [[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]



Comparisions

In [ ]:
d = np.array([1,2,3,4,5])
e = np.array([0,2,6,4,5])

print(d == e,'\n')       # this will make the element wise comparison

d1 = ([1,2,3,4,5])      # this is a list
e1 = ([0,2,6,4,5])
print(d1 == e1,'\n')         # this will make the list wise comparison


print(d > e,'\n')
print(d < e,'\n')

print(d1 > e1,'\n')
print(d1 < e1,'\n')

""" 
Python compares lists lexicographically (like words in a dictionary).
First elements are compared:
    1 vs 0 → since 1 > 0, Python stops there.   [it only compares the first element, and then it stops]
    So d1 > e1 → True
    And d1 < e1 → False
"""


# making array wise comparison -- checks wheather two arrays are equal or not
f = e.copy()
print(f"Array wise comparison : {np.array_equal(d, e)}")
print(f"Array wise comparison : {np.array_equal(e, f)}")


[False  True False  True  True] 

False 

[ True False False False False] 

[False False  True False False] 

True 

False 

Array wise comparison : False
Array wise comparison : True


Logical Operation

In [ ]:
g = np.array([1, 1, 0, 0], dtype=bool)  # if you dont mention the data type as bool then they will be taken as nums
h = np.array([1, 0, 1, 0], dtype=bool)

print(f"LOGICAL OR      : {np.logical_or(g,h)}")       # if any one in idx 0 of both in g and h is 1(true) then true will be printed, as idx 0 in both g and h is 1, hence it printed True in idx 0, SAME GOES FOR OTHER INDEXES
print(f"LOGICAL AND     : {np.logical_and(g,h)}")
print(f"LOGICAL NOT     : {np.logical_not(g)}")        # takes only one array (1 = false, 0 = true)
print(f"LOGICAL XOR     : {np.logical_xor(g,h)}")      # if only one of the two is True then only true will be printed, but not both.

LOGICAL OR      : [ True  True  True False]
LOGICAL AND     : [ True False False False]
LOGICAL NOT     : [False False  True  True]
LOGICAL XOR     : [False  True  True False]
