In [43]:
import numpy as np

x = np.random.randint(1,10, (5,4))

a,b,c,d = x.T

print(x)
print(a)
print(b)
print(c)
print(d)


[[1 1 6 7]
 [2 1 6 7]
 [4 3 2 7]
 [7 7 3 1]
 [1 6 5 7]]
[1 2 4 7 1]
[1 1 3 7 6]
[6 6 2 3 5]
[7 7 7 1 7]
